### Tugas Mg 2

## Generate Data

In [26]:
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
import numpy as np

# Tambah data ke-21
X1 = np.random.normal(loc=1, scale=10, size=(1000, 1))
print("Nilai X1 : ",X1)

# Generate a synthetic classification dataset
X2, y = make_classification(n_samples=1000, n_features=21, n_informative=10, n_redundant=5, n_classes=2, random_state=42)

#Gabungkan data
X = np.hstack((X1, X2))

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

print(f"Shape of X_train: {X_train.shape}")
print(f"Shape of X_test: {X_test.shape}")
print(f"Shape of y_train: {y_train.shape}")
print(f"Shape of y_test: {y_test.shape}")

Nilai X1 :  [[-5.12171953e+00]
 [ 1.33741721e+01]
 [-4.38362044e+00]
 [-9.45742425e+00]
 [-1.07111570e+01]
 [-2.10758183e+01]
 [ 1.42685284e+00]
 [ 6.32669621e+00]
 [-1.30498534e+01]
 [-2.64143169e+00]
 [-1.98549939e+01]
 [-4.18659603e-01]
 [ 4.36075809e+00]
 [ 2.63643308e+00]
 [ 2.82593710e+00]
 [-1.24646580e+01]
 [-8.66280645e+00]
 [ 1.49084490e+00]
 [ 5.25591497e+00]
 [-1.07762548e+01]
 [ 1.28016243e+01]
 [-1.42102691e+01]
 [ 1.95207892e+00]
 [ 1.78131378e+01]
 [ 7.30990776e+00]
 [-5.13882895e+00]
 [ 5.04652714e+00]
 [-5.70165516e+00]
 [ 3.76321476e+00]
 [-9.18898907e+00]
 [ 1.61609751e+01]
 [ 9.12076390e+00]
 [-4.55712002e+00]
 [ 4.50116194e+00]
 [-1.08073218e+01]
 [-1.04686723e+01]
 [ 7.34033035e-01]
 [ 1.50829855e+01]
 [ 1.16567111e+01]
 [ 6.28030457e+00]
 [-4.87547697e+00]
 [ 2.22979258e+00]
 [ 8.28060301e+00]
 [ 1.39023474e+01]
 [ 3.12817270e+00]
 [-4.88211271e+00]
 [-5.07344102e+00]
 [ 6.75496715e+00]
 [ 5.77582805e+00]
 [-7.39957964e-01]
 [ 4.54138738e+00]
 [ 4.00222775e+00]


In [27]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Input

# Initialize the Sequential model with an Input layer
model = Sequential([
    Input(shape=(X_train.shape[1],)) # Explicitly define input shape
])

# Add the first hidden layer
model.add(Dense(units=64, activation='relu'))

# Add a second hidden layer
model.add(Dense(units=32, activation='relu'))

# Add the output layer (1 unit with sigmoid activation for binary classification)
model.add(Dense(units=1, activation='sigmoid'))

# Print the model summary to display the architecture
model.summary()

Model: "sequential_22"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_66 (Dense)                │ (None, 64)             │         1,472 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_67 (Dense)                │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_68 (Dense)                │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 3,585 (14.00 KB)

 Trainable params: 3,585 (14.00 KB)

 Non-trainable params: 0 (0.00 B)

Arsitektur jaringan saraf tiruan terdiri dari 22 neuron input, dua hidden layer masing-masing berisi 64 dan 32 neuron dengan fungsi aktivasi ReLU, serta satu neuron output dengan fungsi aktivasi sigmoid untuk klasifikasi biner. Total parameter yang dipelajari model berjumlah 3.585 yang merupakan bobot dan bias dari seluruh koneksi antar neuron. Struktur ini memungkinkan model melakukan ekstraksi fitur bertahap sebelum menentukan hasil klasifikasi.

## Model

In [28]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

# Fungsi untuk membuat model baru (reset setiap run)
def create_model():
    model = Sequential([
        Dense(64, activation='relu', input_shape=(X_train.shape[1],)),
        Dense(32, activation='relu'),
        Dense(1, activation='sigmoid')
    ])
    model.compile(optimizer='adam',
                  loss='binary_crossentropy',
                  metrics=['accuracy'])
    return model
# Kombinasi parameter
configs = [
    (5, 16),
    (10, 16),
    (5, 32),
    (10, 32)
]
histories = {}
for epochs, batch_size in configs:
    print(f"\nTraining dengan epochs={epochs}, batch_size={batch_size}")

    model = create_model()  # reset model

    history = model.fit(
        X_train, y_train,
        epochs=epochs,
        batch_size=batch_size,
        validation_split=0.2,
        verbose=1
    )
    key = f"epochs_{epochs}_batch_{batch_size}"
    histories[key] = history
print("\nSemua kombinasi training selesai. History tersimpan di 'histories'.")


Training dengan epochs=5, batch_size=16
Epoch 1/5


/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


35/35 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - accuracy: 0.6190 - loss: 0.6425 - val_accuracy: 0.6714 - val_loss: 0.6003
Epoch 2/5
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8368 - loss: 0.4265 - val_accuracy: 0.7571 - val_loss: 0.4978
Epoch 3/5
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8730 - loss: 0.3666 - val_accuracy: 0.8000 - val_loss: 0.4513
Epoch 4/5
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9115 - loss: 0.2750 - val_accuracy: 0.8214 - val_loss: 0.4277
Epoch 5/5
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9316 - loss: 0.2238 - val_accuracy: 0.8500 - val_loss: 0.4137

Training dengan epochs=10, batch_size=16
Epoch 1/10
35/35 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.5863 - loss: 0.7804 - val_accuracy: 0.6571 - val_loss: 0.6003
Epoch 2/10
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7791 - loss: 0.4414 - val_accuracy: 0.7571 - val_loss: 0.4739
Epoch 3/10
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8809 - loss: 0.3362 - val_a

## Prediksi Model

In [29]:
for key, model in models.items():
    print(f"\nPrediksi untuk model: {key}")

    y_pred_proba = model.predict(X_test)
    y_pred_classes = (y_pred_proba > 0.5).astype(int)

    print("First 5 predicted probabilities:")
    print(y_pred_proba[:5].flatten())

    print("First 5 predicted classes:")
    print(y_pred_classes[:5].flatten())


Prediksi untuk model: epochs_5_batch_16
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step 
First 5 predicted probabilities:
[0.5273714  0.8879931  0.998995   0.975324   0.21148047]
First 5 predicted classes:
[1 1 1 1 0]

Prediksi untuk model: epochs_10_batch_16
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step 
First 5 predicted probabilities:
[0.5432634  0.9495318  0.9926891  0.9997118  0.00571024]
First 5 predicted classes:
[1 1 1 1 0]

Prediksi untuk model: epochs_5_batch_32
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step 
First 5 predicted probabilities:
[0.46620122 0.8313634  0.93720126 0.9295322  0.26431084]
First 5 predicted classes:
[0 1 1 1 0]

Prediksi untuk model: epochs_10_batch_32
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step 
First 5 predicted probabilities:
[0.67977583 0.93783754 0.99636483 0.996682   0.03886729]
First 5 predicted classes:
[1 1 1 1 0]


## Evaluasi Model

In [32]:
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score

for key, model in models.items():
    print(f"\n=== Evaluasi untuk {key} ===")

    # Prediksi
    y_pred_proba = model.predict(X_test)
    y_pred_classes = (y_pred_proba > 0.5).astype(int)

    # Confusion Matrix
    cm = confusion_matrix(y_test, y_pred_classes)
    print("Confusion Matrix:")
    print(cm)

    # Metrics
    acc = accuracy_score(y_test, y_pred_classes)
    prec = precision_score(y_test, y_pred_classes)
    rec = recall_score(y_test, y_pred_classes)
    f1 = f1_score(y_test, y_pred_classes)

    print(f"Accuracy  : {acc:.4f}")
    print(f"Precision : {prec:.4f}")
    print(f"Recall    : {rec:.4f}")
    print(f"F1-Score  : {f1:.4f}")


=== Evaluasi untuk epochs_5_batch_16 ===
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step 
Confusion Matrix:
[[141  17]
 [ 12 130]]
Accuracy  : 0.9033
Precision : 0.8844
Recall    : 0.9155
F1-Score  : 0.8997

=== Evaluasi untuk epochs_10_batch_16 ===
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step 
Confusion Matrix:
[[145  13]
 [ 13 129]]
Accuracy  : 0.9133
Precision : 0.9085
Recall    : 0.9085
F1-Score  : 0.9085

=== Evaluasi untuk epochs_5_batch_32 ===
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step 
Confusion Matrix:
[[136  22]
 [ 17 125]]
Accuracy  : 0.8700
Precision : 0.8503
Recall    : 0.8803
F1-Score  : 0.8651

=== Evaluasi untuk epochs_10_batch_32 ===
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step 
Confusion Matrix:
[[142  16]
 [ 17 125]]
Accuracy  : 0.8900
Precision : 0.8865
Recall    : 0.8803
F1-Score  : 0.8834
